name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: Windows

    steps:
      - uses: actions/checkout@v3

      - name: ... buil success ...
        run: echo ... buil success ...

      - name: ... check node version ...
        run: node -v 
  
  tests:
    name: Tests
    runs-on: Windows

    steps:
      - name: ... tests success ...
        run: echo ... test success ...

  deploy:
    name: Deploy
    runs-on: Windows

    steps:
      - name: ... deploy success ...
        run: echo ... deploy success ...   

  cleanUp:
    name: Clean up
    runs-on: Windows

    steps:
      - name: ... clean up success ...
        run: echo ... clean up success ...      
